### ISSUE TITLE
site.webmanifests does not link to asset paths

### ISSUE THREAD

**Issue by cbetta** [RealFaviconGenerator/rails_real_favicon#26]
The generated `site.webmanifest` looks something like this:

```json
{
    "name": "App Name",
    "short_name": "App Name",
    "icons": [
        {
            "src": "android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#3F4550",
    "background_color": "#3F4550",
    "start_url": "/",
    "display": "standalone"
}
```

As a result, when shipping through Rails, the icon paths are still hard coded and can't be found. The right things is to generate a `site.webmanifest.erb` file, and update the paths to use the asset path helper.

```erb
{
    "name": "App Name",
    "short_name": "App Name",
    "icons": [
        {
            "src": "<%= asset_path 'favicon/android-chrome-192x192.png' %>",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "<%= asset_path 'favicon/android-chrome-512x512.png' %>",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#3F4550",
    "background_color": "#3F4550",
    "start_url": "/",
    "display": "standalone"
}
```

As a result, the `_favicon.html.erb` needs to be updated to link to a `.txt` file instead oddly.

```erb
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest.txt' %>">
```

**Comment by phbernard** [comment]
Thank you for reporting.

Gem v0.0.8 should fix the issue: generated `site.webmanifest` is using `asset_path`, as expected.

**Comment by cbetta** [comment]
👍

**Comment by cbetta** [comment]
Not sure this works. I am using v0.0.8 and it generates a `site.webmanifest.erb` now, with this content for me:

```json
{
    "name": "App Name",
    "short_name": "App Name",
    "icons": [
        {
            "src": "android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#3F4550",
    "background_color": "#3F4550",
    "start_url": "https://mydomain.com",
    "display": "standalone"
}
```

The precompiled site manifest still doesn't use asset path.

**Comment by phbernard** [comment]
Damn! This is due to https://github.com/RealFaviconGenerator/realfavicongenerator/issues/270. I didn't realize the issue early today because I run it against an old copy of `favicon.json` (prior package v0.16).

Alright, v0.0.9 published, re-run with a fresh project *and* fresh favicon got from https://realfavicongenerator.net/favicon/ruby_on_rails. It works, `site.webmanifest.erb` contains references to `asset_path`.

Sorry for the roundtrip.

**Comment by cbetta** [comment]
This still seems to be missing my last point though. Adding a `.erb` means the file gets compiled as "site.webmanifest-[hash].txt" instead of `site-[hash].webmanifest`.

In my solution, I added a `.txt` in the `_favicon.html.erb` file, but there might be another way to register `.webmanifest` as an extension.

**Comment by phbernard** [comment]
When running the [Rails procedure](https://realfavicongenerator.net/favicon/ruby_on_rails) on a fresh Rails 5.1.5 app, here is what I observe:

- `app/views/application/_favicon.html.erb` references the manifest with:

      <link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">

- When the partial is rendered, the line above becomes: (it has the final `.txt` extension, as you mention)

      <link rel="manifest" href="/assets/favicon/site.webmanifest-a5839a3570040282686561dfbf45870935a5b946c9660d7ed14838c86458f3d6.txt">

- If I visit the link above (`http://127.0.0.1:3000/assets/favicon/site.webmanifest-a5839a3570040282686561dfbf45870935a5b946c9660d7ed14838c86458f3d6.txt`), I get the manifest, as expected:

      {
          "name": "",
          "short_name": "",
          "icons": [
              {
                  "src": "/assets/favicon/android-chrome-192x192-adb23fae0554a51fcc7496d156cd5019ca2ee625ca7e1f06e8897ed135153732.png",
                  "sizes": "192x192",
                  "type": "image/png"
              },
              {
                  "src": "/assets/favicon/android-chrome-512x512-458cca9d7c337d38070e454a7497fec77969e6dc7fe94d9d306171ad505b41ab.png",
                  "sizes": "512x512",
                  "type": "image/png"
              }
          ],
          "theme_color": "#ffffff",
          "background_color": "#ffffff",
          "display": "standalone"
      }

Although this is not the perfect behavior of having a true `site.webmanifest` file, the solution works. In particular, I didn't have to edit `_favicon.html.erb`.

But you seem to face a different situation?

**Comment by cbetta** [comment]
Hmmm. 

Just out of interest, how do you test the asset pipeline on your development machine? I'm mainly observing what happens when I deploy the app.

**Comment by cbetta** [comment]
So to clarify, in my case the mmanifests gets compiles as `site.webmanifest-[hash].txt`, but when rendering the view throws an error:

```
Sprockets::Rails::Helper::AssetNotFound in Sessions#new
Showing /Users/cbetta/code/workbetta/app-name/app/views/application/_favicon.html.erb where line #4 raised:

The asset "favicon/site.webmanifest" is not present in the asset pipeline.
```

And as soon as I add the `.txt` in the `_favicon.html.erb` it all renders fine.

---

FYI I am on Ruby 2.5.0 and Rails 5.1.5

**Comment by phbernard** [comment]
Asset pipeline in dev mode: this is the default I get immediately after running `rails new MyApp` (I'm running Rails 5.1.5). I *suppose* this is because the default value for `assets.debug` is `true`, yet your should make your own experiments to find out for sure.

Alright, I now reproduce the issue by tuning my development environment with:

      config.assets.compile = false
      config.assets.debug = false

and precompile the assets manually with:

      rake assets:precompile

I could fix this by registering the `.webmanifest` extension in `config/application.rb`:

    config.assets.configure do |env|
      env.register_mime_type('application/manifest+json', extensions: ['.webmanifest'])
    end

With this code, `rake assets:precompile` now keeps the `.webmanifest` extension (instead of appending a `.txt` extension).

Before I implement something, could you tell me if that works on your side?

**Comment by cbetta** [comment]
I added that content to the `config/application.rb`, and recompiled the assets, and now it works!

I assume you want to add this to the gem?

**Comment by phbernard** [comment]
Yup! Freshly published version 0.0.10 generates `config/initializers/web_app_manifest.rb`. No need to modify `config/application.rb`. Does it work for you?

**Comment by cbetta** [comment]
Works like a charm!

**Comment by phbernard** [comment]
Great! Woaw, that was a long thread! :)

**Comment by jklimke** [comment]
I am currently using the gem with rails 6.0 and i am experiencing a similar problem. The mime type registration is executed on app initialization but the asset precompilation creates a file `site.webmanifest.html-d2e0de9cfe7d9866c34d98f77c6881a9807f596bb29f8cae1b554166e64a589d.erb`in the public/assets/favicon folder.

It sounds like a similar problem. Any idea how to handle this issue ?

**Comment by maia** [comment]
@jklimke see #35

**Comment by molfar** [comment]
I have the same error with latest Rails 6.0.3.4

**Comment by leehericks** [comment]
Registering the mime type used to help...now I'm back to the same error in 6.0.3.4 as well.

**Comment by k00ka** [comment]
+1 on 6.0.3.4
